/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as import0 from '@angular/core';
import * as import3 from './create.component';
export declare const RenderType_FormioResourceCreateComponent: import0.RendererType2;
export declare function View_FormioResourceCreateComponent_0(l: any): import0.ɵViewDefinition;
export declare const FormioResourceCreateComponentNgFactory: import0.ComponentFactory<import3.FormioResourceCreateComponent>;
