/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as import0 from '@angular/core';
import * as import2 from './index.component';
export declare const RenderType_FormioResourceIndexComponent: import0.RendererType2;
export declare function View_FormioResourceIndexComponent_0(l: any): import0.ɵViewDefinition;
export declare const FormioResourceIndexComponentNgFactory: import0.ComponentFactory<import2.FormioResourceIndexComponent>;
