/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as import0 from '@angular/core';
import * as import3 from './resource.component';
export declare const RenderType_FormioResourceComponent: import0.RendererType2;
export declare function View_FormioResourceComponent_0(l: any): import0.ɵViewDefinition;
export declare const FormioResourceComponentNgFactory: import0.ComponentFactory<import3.FormioResourceComponent>;
