/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as import0 from '@angular/core';
import * as import6 from './view.component';
export declare const RenderType_FormioResourceViewComponent: import0.RendererType2;
export declare function View_FormioResourceViewComponent_0(l: any): import0.ɵViewDefinition;
export declare const FormioResourceViewComponentNgFactory: import0.ComponentFactory<import6.FormioResourceViewComponent>;
