/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as import0 from '@angular/core';
import * as import1 from './register.component';
export declare const RenderType_FormioAuthRegisterComponent: import0.RendererType2;
export declare function View_FormioAuthRegisterComponent_0(l: any): import0.ɵViewDefinition;
export declare const FormioAuthRegisterComponentNgFactory: import0.ComponentFactory<import1.FormioAuthRegisterComponent>;
