/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as import0 from '@angular/core';
import * as import4 from './grid.component';
export declare const RenderType_FormioGridComponent: import0.RendererType2;
export declare function View_FormioGridComponent_0(l: any): import0.ɵViewDefinition;
export declare const FormioGridComponentNgFactory: import0.ComponentFactory<import4.FormioGridComponent>;
