/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as import0 from '@angular/core';
import * as import2 from './formio.alerts';
export declare const RenderType_FormioAlertsComponent: import0.RendererType2;
export declare function View_FormioAlertsComponent_0(l: any): import0.ɵViewDefinition;
export declare const FormioAlertsComponentNgFactory: import0.ComponentFactory<import2.FormioAlertsComponent>;
